"""empty message

Revision ID: 1f9bb05708b8
Revises: ab32a7d554e1
Create Date: 2023-06-07 02:56:59.717237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9bb05708b8'
down_revision = 'ab32a7d554e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cate', sa.Text(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('cate')

    # ### end Alembic commands ###
