"""empty message

Revision ID: 2a0dc91dc978
Revises: e94b44a5ae78
Create Date: 2023-06-07 20:25:56.274695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0dc91dc978'
down_revision = 'e94b44a5ae78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bool_bad_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bool_id'], ['bool.id'], name=op.f('fk_bool_bad_voter_bool_id_bool'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bool_bad_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bool_id', name=op.f('pk_bool_bad_voter'))
    )
    op.create_table('bool_good_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bool_id'], ['bool.id'], name=op.f('fk_bool_good_voter_bool_id_bool'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bool_good_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bool_id', name=op.f('pk_bool_good_voter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bool_good_voter')
    op.drop_table('bool_bad_voter')
    # ### end Alembic commands ###
