"""empty message

Revision ID: e94b44a5ae78
Revises: 905b69a61dc8
Create Date: 2023-06-07 03:17:11.504746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94b44a5ae78'
down_revision = '905b69a61dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bool', schema=None) as batch_op:
        batch_op.alter_column('cate',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bool', schema=None) as batch_op:
        batch_op.alter_column('cate',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
