"""empty message

Revision ID: eed1484071f0
Revises: 139caa0fd3af
Create Date: 2023-06-07 03:05:51.823203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed1484071f0'
down_revision = '139caa0fd3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cate', sa.Text(), nullable=False))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('cate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cate', sa.TEXT(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('bool', schema=None) as batch_op:
        batch_op.drop_column('cate')

    # ### end Alembic commands ###
